plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ahmetkaragoz.ucbeyleri'
    compileSdk 34

    defaultConfig {
        applicationId "com.ahmetkaragoz.ucbeyleri"
        minSdk 24
        targetSdk 34
        versionCode((System.getenv("GITHUB_RUN_NUMBER") ?: "1").toInteger() + 10)
        versionName "0.9." + (System.getenv("GITHUB_RUN_NUMBER") ?: "0")
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
